---
title: "Fall2020Plans"
author: "Sarah Gillespie"
date: "6/15/2020"
output: html_document
---
```{r include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# setting up the file
require(knitr)
opts_chunk$set(
  tidy=TRUE,                     # display code as typed
  size="small",                   # slightly smaller font for code
  tidy.opts=list(width.cutoff=65), # wrap text and long comments
  fig.width=7, fig.height=5           #figure size
)

knitr::opts_chunk$set(echo = TRUE)

```

```{r include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
require(tidyverse)
require(mosaic)
require(mosaicData)
require(lmtest)
library(ggthemes)
library(formatR)
library(gmodels) 
library(Hmisc)
```


```{r include=FALSE, warning=FALSE, message=FALSE, error=FALSE}

#read in the article data
fall2020dataCoHEJun16 <- read_csv("fall2020dataCoHEJun16.csv")

#remove any doubles in the article's data
fall2020dataCoHEJun16 <- unique(fall2020dataCoHEJun16)

#separate anything with a dash, like California State University-Fresno with the specific campus being campus1
fall2020dataCoHEJun16 <- fall2020dataCoHEJun16 %>%
  separate(Institution, c("mainname", "campus1"), " — ")

#fall2020dataCoHEJun16 <- fall2020dataCoHEJun16[!duplicated(fall2020dataCoHEJun16$mainname), ]

#read in government data
Most_Recent_Cohorts_SMALL <- read_csv("Most-Recent-Cohorts-SMALL.csv")

#rename the school name to be institution
Most_Recent_Cohorts_SMALL <- rename(Most_Recent_Cohorts_SMALL, Institution = INSTNM)

#separate anything with a dash, like California State University-Fresno with the specific campus being campus2 that is then removed
Most_Recent_Cohorts_SMALL <- Most_Recent_Cohorts_SMALL %>%
  separate(Institution, c("mainname", "campus2"), "-") %>%
  select(-campus2)

Most_Recent_Cohorts_SMALL <- Most_Recent_Cohorts_SMALL[!duplicated(Most_Recent_Cohorts_SMALL$mainname), ]
 

KaggleRegions <- read_csv("KaggleRegions_datasets_31195_39789_states.csv")

KaggleRegions <- rename(KaggleRegions, StateL = State)

KaggleRegions <- rename(KaggleRegions, "State" = "State Code")

bigList<-merge(x=fall2020dataCoHEJun16,y=Most_Recent_Cohorts_SMALL,by="mainname",all.x=TRUE)

bigList<-merge(x=bigList,y=KaggleRegions,by="State",all.x=TRUE)

bigList<-bigList[!is.na(bigList$STABBR),]



List <- bigList %>%
  separate(Category, c("linkish", "Call1"), ">") %>%
  separate(Call1, c("Call", "extra"), "<") %>%
  select(-linkish, -extra, -UNITID, -OPEID, -OPEID6, -DISTANCEONLY, -RELAFFIL, -HCM2, -CCSIZSET, -CCUGPROF, -CCBASIC)

#makes decision all lowercase
List[[5]] <- tolower(List[[5]])

#2016 election results
X2016results <- read_csv("2016results.csv")

X2016results <- rename(X2016results, StateL = State)


#join election results to each school by state

List<-merge(x=List,y=X2016results,by="StateL",all.x=TRUE)
```

```{r warning=FALSE, message=FALSE, error=FALSE}

#ALL STATES ALL SCHOOLS INCLUDING SOME GRAD SCHOOLS

#by state

# ggplot(List, aes(y = State)) +
#  geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))

#region

ggplot(List, aes(y = Region)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE)) +
  labs(title="Colleges fall 2020 call by Region") +
  theme_few()

#division

ggplot(List, aes(y = Division)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE)) +
  labs(title="Colleges fall 2020 call by Division") +
  theme_few()

#public vs. private

ggplot(List, aes(y = Control)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))  +
  labs(title="Public vs. Private school fall 2020 call") +
  theme_few()

#all colleges choices

ggplot(List, aes(y = Call)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))  +
  labs(title="All schools fall 2020 call") +
  theme_few()

#women only
WomenOnly <- List %>%
  filter(WOMENONLY == 1)

ggplot(WomenOnly, aes(y = Call)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE)) +
  labs(title="Historically Women's Colleges fall 2020 call") +
  theme_few()


#Massachusetts only

MassOnly <- List %>%
  filter(State == "MA")

ggplot(MassOnly, aes(y = Call)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE)) +
  labs(title="Massachusetts schools fall 2020 call") +
  theme_few()
```

```{r warning=FALSE, message=FALSE, error=FALSE}

#scatterplots


List$ADM_RATE <- as.numeric(as.character(List$ADM_RATE))
List$MEDIAN_HH_INC <- as.numeric(as.character(List$MEDIAN_HH_INC))
List$POVERTY_RATE <- as.numeric(as.character(List$POVERTY_RATE))
List$UGDS <- as.numeric(as.character(List$UGDS))
List$percR <- as.numeric(as.character(List$percR))
List$ADM_RATE <- as.numeric(as.character(List$ADM_RATE))
List$PCT_BORN_US <- as.numeric(as.character(List$PCT_BORN_US))


#admin rate and median HH income
ggplot(List, aes(x = ADM_RATE, y = MEDIAN_HH_INC, color = Call)) +
  geom_point() +
  scale_y_continuous(labels = scales::comma) +
  labs(title="Median Household Income, acceptance rate, and fall 2020 call") +
  theme_few()

#admin rate and poverty rate

# ggplot(List, aes(x = ADM_RATE, y = POVERTY_RATE, color = Call)) +
#   geom_point() +
#   scale_y_continuous(labels = scales::comma)

#admin rate and number of undergrad students

# ggplot(List, aes(x = ADM_RATE, y = UGDS, color = Call)) +
#   geom_point() +
#   scale_y_continuous(trans = 'log10')

#admin rate and percentage of students born inside the United States
ggplot(List, aes(x = ADM_RATE, y = PCT_BORN_US, color = Call)) +
  geom_point() +
  scale_y_continuous(trans = 'log10') +
  ylim(65,100) +
  labs(title="Percent of students born in the U.S., acceptance rate, and fall 2020 call") +
  theme_few()

```



```{r warning=FALSE, message=FALSE, error=FALSE}

# selective schools: I define this as schools with an acceptance rate of <25%.

SelectiveSchool <- List

SelectiveSchool <- data.frame(lapply(SelectiveSchool, function(x) {
                  gsub("NULL", "", x)}))

SelectiveSchool$percR <- as.numeric(as.character(SelectiveSchool$percR))
SelectiveSchool$ADM_RATE <- as.numeric(as.character(SelectiveSchool$ADM_RATE))
SelectiveSchool$SAT_AVG <- as.numeric(as.character(SelectiveSchool$SAT_AVG))

SelectiveSchool <- SelectiveSchool %>%
  filter(ADM_RATE < 0.25)


#by state

# ggplot(SelectiveSchool, aes(y = State)) +
#  geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))

#region

ggplot(SelectiveSchool, aes(y = Region)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))+
  labs(title="Selective schools fall 2020 call by region") +
  theme_few()

#division

# ggplot(SelectiveSchool, aes(y = Division)) +
#  geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))

#public vs. private

# ggplot(SelectiveSchool, aes(y = Control)) +
#  geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))

#all colleges choices

# ggplot(SelectiveSchool, aes(y = Call)) +
#  geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE))

#massachusetts only

MassOnly <- SelectiveSchool %>%
  filter(State == "MA")

ggplot(MassOnly, aes(y = Call)) +
 geom_bar(aes(fill = Call), position = position_stack(reverse = FALSE)) +
  labs(title="Massachusetts selective schools fall 2020 call") +
  theme_few()

#admin rate and state's politcal lean

# ggplot(SelectiveSchool, aes(x = ADM_RATE, y = percR, color = Call)) +
#   geom_point()


```

